// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AsyncBtn: typeof import('./src/components/globals/AsyncBtn.vue')['default']
    Carrusel: typeof import('./src/components/globals/Carrusel.vue')['default']
    CircularMenu: typeof import('./src/components/globals/CircularMenu.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    FeatureCard: typeof import('./src/components/Home/FeatureCard.vue')['default']
    Features: typeof import('./src/components/Home/Features.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    FriendReqCard: typeof import('./src/components/globals/FriendReqCard.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Hero: typeof import('./src/components/Home/Hero.vue')['default']
    InteractionBtns: typeof import('./src/components/feed/InteractionBtns.vue')['default']
    OptionsBtn: typeof import('./src/components/globals/OptionsBtn.vue')['default']
    PostCard: typeof import('./src/components/feed/PostCard.vue')['default']
    RequestCard: typeof import('./src/components/globals/RequestCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
